name: 🎈其他相关
title: '🎈'
description: 确定不是上面两种类型，同 oas 相关的一切
labels: ['未来可期']
body:
  - type: textarea
    id: describe
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 其他内容
      description: 关于这个issue的相关内容
    validations:
      required: false
